services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - app_network

  server1:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: server1
    ports: 
      -"8001:8000"
    depends_on:
      - redis
    restart: unless-stopped
    volumes: 
      - ./:/app
    networks: 
      - app_network
    environment:
      - MONGODB_URI=mongodb+srv://ahmedanis4546:ahmed123@cluster0.tvtr7.mongodb.net/Reels_Pro
      - SERVER_ID=server-1
      - REDIS_HOST=redis
      - PORT=6379
      - PASSWORD=KbPfKbby73xgT98Ae9LosnwtnP7ptb8P

  server2:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: server2
    ports: 
      -"8002:8000"
    depends_on:
      - redis
    restart: unless-stopped
    volumes: 
      - ./:/app
    networks: 
      - app_network
    environment:
      - MONGODB_URI=mongodb+srv://ahmedanis4546:ahmed123@cluster0.tvtr7.mongodb.net/Reels_Pro
      - SERVER_ID=server-2
      - REDIS_HOST=redis
      - PORT=6379
      - PASSWORD=KbPfKbby73xgT98Ae9LosnwtnP7ptb8P    

  server3:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: server1
    ports: 
      -"8003:8000"
    depends_on:
      - redis
    restart: unless-stopped
    volumes: 
      - ./:/app
    networks: 
      - app_network
    environment:
      - MONGODB_URI=mongodb+srv://ahmedanis4546:ahmed123@cluster0.tvtr7.mongodb.net/Reels_Pro
      - SERVER_ID=server-3
      - REDIS_HOST=redis
      - PORT=6379
      - PASSWORD=KbPfKbby73xgT98Ae9LosnwtnP7ptb8P

  redis:
    image: redis
    container_name: redis
    ports: 
      - "6379:6379"
    restart: always
    volumes: 
      - redis_data:/data
    networks: 
      - app_network
    command: ["redis-server", "requirepass", "KbPfKbby73xgT98Ae9LosnwtnP7ptb8P"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    ports: 
      - "5672:5672"   
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
    networks: 
      - app_network
    environment:
      RABBITMQ_DEFAULT_USER: admin      
      RABBITMQ_DEFAULT_PASS: admin123    

volumes: 
  redis_data:
  rabbitmq_data:


nerworks: 
  app_network: 
    driver: bridge