import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "../components/Provider";
import Navbar from "./co/Navbar";
import Sidebar from "./co/Sidebar";
import Footer from "./co/Footer";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "./context/themeContext";
import { ProfileProvider } from "./context/profileContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reel_Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (  
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}  suppressHydrationWarning >
      {/* <ThemeProvider> */}
      {/* </ThemeProvider> */}
        <ProfileProvider>
          <Provider>
              { children }
            <Toaster position="top-right" />
          </Provider>
        </ProfileProvider>
    </body>
  </html>

  );
}
