import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "../components/Provider";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "./context/themeContext";
import { ProfileProvider } from "./context/profileContext";
import { SocketProvider } from "./context/SocketContext";
import { UserProvider } from "./context/userContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Reel_Pro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (  
  <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}  suppressHydrationWarning >
      <Provider>
        <UserProvider>
          <SocketProvider>
            {/* <ThemeProvider> */}
              <ProfileProvider>
                    { children }
                  <Toaster position="top-right" />
              </ProfileProvider>
            {/* </ThemeProvider> */}
          </SocketProvider>
        </UserProvider>
      </Provider>
    </body>
  </html>
  );
}
